In [1]:
# =========================
# NOTEBOOK VERSION
# =========================
NOTEBOOK_VERSION = "2026.06.30.1"
NOTEBOOK_VERSION_TIMESTAMP = "2026-06-30T16:15:00+08:00"

import os
import pandas as pd
import re
from pathlib import Path

try:
    from google.colab import drive
    IN_COLAB = True
except ModuleNotFoundError:
    drive = None
    IN_COLAB = False

# =========================
# CONFIG
# =========================
MODE = "auto"  # "auto", "local", or "google"

if MODE == "auto":
    MODE = "google" if IN_COLAB else "local"

if MODE == "local":
    FILE_PATH = r"ac-test.xlsx"  # local workbook in repo root
    OUTPUT_CSV = r"new-template.csv"  # local output CSV in repo root
    SHARED_PATH = r"."
elif MODE == "google":
    if not IN_COLAB:
        raise RuntimeError("Google mode requires Google Colab runtime")
    if not os.path.ismount('/content/drive'):
        drive.mount('/content/drive', force_remount=False)
    FILE_PATH = r"/content/drive/MyDrive/dream/rates/wip/ac-test.xlsx"
    OUTPUT_CSV = r"/content/drive/MyDrive/dream/pauline/custom/new-template.csv"
    SHARED_PATH = r"/content/drive/MyDrive/dream/rates"
else:
    raise ValueError("MODE must be 'auto', 'local', or 'google'")

SECTION_TO_COL = {
    "SEDAN": "pass",
    "SUV / LIGHT COMMERCIAL": "lcv",
}

In [2]:
# Manual label overrides for carrier-specific sheet names and custom aliases.
LOCATION_MAP = {
    # Full names (with carrier)
    "Melbourne Autocare": {"name": "MELBOURNE, VIC", "state": "VIC", "loc": "MELBOURNE"},
    "Sydney Autocare Dapto": {"name": "WOLLONGONG, NSW", "state": "NSW", "loc": "WOLLONGONG"},
    "Sydney Autocare Prestons": {"name": "SYDNEY, NSW", "state": "NSW", "loc": "SYDNEY"},
    "Brisbane Autocare": {"name": "BRISBANE, QLD", "state": "QLD", "loc": "BRISBANE"},
    "Townsville Autocare": {"name": "TOWNSVILLE, QLD", "state": "QLD", "loc": "TOWNSVILLE"},
    "Adelaide Autocare": {"name": "ADELAIDE, SA", "state": "SA", "loc": "ADELAIDE"},
    "Perth Autocare": {"name": "PERTH, WA", "state": "WA", "loc": "PERTH"},
    "Darwin Autocare": {"name": "DARWIN, NT", "state": "NT", "loc": "DARWIN"},
    "Devonport Autocare": {"name": "DEVONPORT, TAS", "state": "TAS", "loc": "DEVONPORT"},
    "Hobart Autocare": {"name": "HOBART, TAS", "state": "TAS", "loc": "HOBART"},
    "Sprint Mufflers Alice Springs": {"name": "ALICE SPRINGS, NT", "state": "NT", "loc": "ALICE SPRINGS"},
    "Sprint Mufflers - Alice Springs": {"name": "ALICE SPRINGS, NT", "state": "NT", "loc": "ALICE SPRINGS"},
    "Meteor Cairns": {"name": "CAIRNS, QLD", "state": "QLD", "loc": "CAIRNS"},
    "Meteor - Cairns": {"name": "CAIRNS, QLD", "state": "QLD", "loc": "CAIRNS"},
    "Meteor Mt Isa": {"name": "MT ISA, QLD", "state": "QLD", "loc": "MT ISA"},
    "Meteor - Mt Isa": {"name": "MT ISA, QLD", "state": "QLD", "loc": "MT ISA"},

    # Manual aliases (where sheet labels differ from canonical locality output).
    "Mt Isa": {"name": "MT ISA, QLD", "state": "QLD", "loc": "MT ISA"},
    "Mount Isa": {"name": "MT ISA, QLD", "state": "QLD", "loc": "MT ISA"},
    "Palmview": {"name": "SUNSHINE COAST, QLD", "state": "QLD", "loc": "SUNSHINE COAST"},
    "Sunshine Coast": {"name": "SUNSHINE COAST, QLD", "state": "QLD", "loc": "SUNSHINE COAST"},
}

STATE_CODES = {"NSW", "VIC", "QLD", "SA", "WA", "TAS", "NT", "ACT"}
LOCALITY_MAP_PATH = (Path(SHARED_PATH) / "mappers" / "locations.xlsx") if MODE == "google" else None


def _normalize_label_key(value):
    return re.sub(r"\s+", " ", str(value)).strip().upper()


def load_locality_state_map(path: Path | None, debug=True):
    """Load locality -> state reference data from locations.xlsx."""
    if path is None:
        if debug:
            print("[INFO] Locality mapper import skipped (mode=local); using manual overrides fallback")
        return {}, {}

    if not path.exists():
        if debug:
            print(f"[WARN] Locality mapper not found: {path}")
        return {}, {}

    loc_df = pd.read_excel(path)
    required = {"locality", "state"}
    if not required.issubset(loc_df.columns):
        missing = sorted(required - set(loc_df.columns))
        raise ValueError(f"Missing columns in locality mapper: {missing}")

    loc_df = loc_df[["locality", "state"]].dropna(subset=["locality", "state"])
    loc_df["locality"] = loc_df["locality"].map(_normalize_label_key)
    loc_df["state"] = loc_df["state"].astype(str).str.strip().str.upper()
    loc_df = loc_df[loc_df["state"].isin(STATE_CODES)]

    # Choose state by highest row count per locality.
    # If there is a tie for highest count, keep locality ambiguous.
    state_counts = (
        loc_df.groupby(["locality", "state"], dropna=False)
        .size()
        .reset_index(name="count")
    )

    locality_state_map = {}
    locality_ambiguous_map = {}

    for locality, group in state_counts.groupby("locality"):
        max_count = int(group["count"].max())
        top_states = sorted(group.loc[group["count"] == max_count, "state"].tolist())
        if len(top_states) == 1:
            locality_state_map[locality] = top_states[0]
        else:
            locality_ambiguous_map[locality] = top_states

    if debug:
        print(f"[INFO] Loaded {len(locality_state_map)} locality states by highest frequency from {path}")
        if locality_ambiguous_map:
            print(
                f"[WARN] {len(locality_ambiguous_map)} localities have top-count ties across states; "
                "add manual overrides for these names"
            )

    return locality_state_map, locality_ambiguous_map


LOCALITY_STATE_MAP, LOCALITY_AMBIGUOUS_MAP = load_locality_state_map(LOCALITY_MAP_PATH, debug=True)

In [3]:


# =========================
# CARRIER MAPPING
# =========================
# Pattern-based mapping (regex) - checked in order, first match wins
CARRIER_PATTERNS = [
    (r"(?i)\bA1\b", "A1"),
    (r"(?i)ace\s*car\s*carriers", "Ace Car Carriers"),
    (r"(?i)alfies\s*towing", "Alfies Towing"),
    (r"(?i)autocare\s*tas", "Autocare TAS"),
    (r"(?i)autocare", "Autocare"),
    (r"(?i)patricks?\s*goods", "Patricks Goods"),
    (r"(?i)automover", "Automover"),
    (r"(?i)broome\s*car\s*carriers", "Broome Car Carriers"),
    (r"(?i)byron\s*bay\s*towing", "Byron Bay Towing"),
    (r"(?i)cairns\s*car\s*carriers", "Cairns Car Carriers"),
    (r"(?i)capital\s*towing", "Capital Towing"),
    (r"(?i)carways", "Carways"),
    (r"(?i)\bceva\b", "Ceva"),
    (r"(?i)coastal\s*auto", "Coastal Auto"),
    (r"(?i)craig\s*glasson", "Craig Glasson"),
    (r"(?i)dynamic\s*car\s*carry", "Dynamic Car Carrying"),
    (r"(?i)easyway", "Easyway"),
    (r"(?i)\bgclh\b", "GCLH"),
    (r"(?i)\bgls\b", "GLS"),
    (r"(?i)gold\s*coast\s*car\s*carriers", "Gold Coast Car Carriers"),
    (r"(?i)gttkal", "GTTKAL"),
    (r"(?i)hazellbros", "Hazellbros"),
    (r"(?i)iat\s*transport", "IAT Transport"),
    (r"(?i)haul\s*car", "Haul Car"),
    (r"(?i)hunter\s*united", "Hunter United"),
    (r"(?i)jcs\s*express", "JCS Express"),
    (r"(?i)shipping", "Shipping"),
    (r"(?i)john\s*scobie", "John Scobie"),
    (r"(?i)jolly\s*(&|and)?\s*sons", "Jolly & Sons"),
    (r"(?i)\bla\s*car\s*carriers", "LA Car Carriers"),
    (r"(?i)lobeys?\s*transport", "Lobeys TRansport"),
    (r"(?i)mackay\s*car\s*(&|and)?\s*commercial", "Mackay Car & Commercial"),
    (r"(?i)melcrest", "Melcrest"),
    (r"(?i)\bmn\s*car\s*carriers", "MN Car Carriers"),
    (r"(?i)mick\s*reeve", "Mick Reeve Carriers"),
    (r"(?i)mt\s*andrews", "MT Andrews"),
    (r"(?i)nicks?\s*budget", "Nicks Budget"),
    (r"(?i)nicks?\s*express", "Nicks Express"),
    (r"(?i)newcastle\s*vehicle\s*transport|nvt", "Newcastle Vehicle Transporters"),
    (r"(?i)northern\s*vic\s*car\s*transport", "Northern Vic Car TRansport"),
    (r"(?i)\bonit\b", "Onit"),
    (r"(?i)prixcar\s*spokes", "Prixcar Spokes"),
    (r"(?i)prixcar", "Prixcar"),
    (r"(?i)progressive", "Progressive"),
    (r"(?i)reardons?", "Reardons"),
    (r"(?i)red\s*centre\s*towing", "Red Centre Towing"),
    (r"(?i)rowdys?", "Rowdys"),
    (r"(?i)saferun", "Saferun"),
    (r"(?i)searoad", "Searoad"),
    (r"(?i)\bsmb\b", "SMB"),
    (r"(?i)south\s*west\s*car\s*carriers", "South West Car Carriers"),
    (r"(?i)speedy", "Speedy"),
    (r"(?i)spoke\s*extras", "Spoke Extras"),
    (r"(?i)tamworth\s*car\s*carriers", "Tamworth Car Carriers"),
    (r"(?i)tge\s*car\s*carry", "TGE Car Carrying"),
    (r"(?i)tidy\s*towing", "Tidy Towing"),
    (r"(?i)top\s*end\s*car\s*carriers", "TopEnd Car Carriers"),
    (r"(?i)western\s*vehicle\s*movers", "Western Vehicle Movers"),
    (r"(?i)sim\s*cam", "Sim Cam"),
    (r"(?i)way\s*2\s*go", "Way 2 Go"),
    (r"(?i)westoz", "Westoz"),
]

DEFAULT_CARRIER = "UNKNOWN"


def get_carrier_from_sheet_name(sheet_name: str) -> str:
    """Return carrier name based on sheet name pattern matching."""
    for pattern, carrier in CARRIER_PATTERNS:
        if re.search(pattern, sheet_name):
            return carrier
    return DEFAULT_CARRIER

In [4]:
def is_text_label(x):
    """Check if value is a text label (contains letters)."""
    return pd.notna(x) and isinstance(x, str) and any(ch.isalpha() for ch in x)


def parse_money(x):
    """Parse monetary value from cell (handles $, commas, etc)."""
    if pd.isna(x):
        return None
    if isinstance(x, (int, float)):
        return float(x)
    if isinstance(x, str):
        s = x.strip().replace("$", "").replace(",", "")
        if not s:
            return None
        try:
            return float(s)
        except ValueError:
            return None
    return None


def clean_text(s):
    """Normalize whitespace in text."""
    return re.sub(r"\s+", " ", str(s)).strip()


LOCATION_MAP_NORMALIZED = {
    clean_text(k).upper(): v for k, v in LOCATION_MAP.items()
}


def normalize_location(raw_label: str):
    """Convert raw location label to canonical name, state, and loc (all uppercase)."""
    raw_label = clean_text(raw_label)
    normalized_label = raw_label.upper()

    # 1) Manual overrides (carrier-specific names and explicit aliases).
    if normalized_label in LOCATION_MAP_NORMALIZED:
        m = LOCATION_MAP_NORMALIZED[normalized_label]
        return m["name"], m["state"], m["loc"]

    # 2) If already CITY, ST, keep it.
    m = re.match(r"^\s*(.+?)\s*,\s*([A-Z]{2,3})\s*$", normalized_label)
    if m and m.group(2) in STATE_CODES:
        city, state = m.group(1).strip().upper(), m.group(2).upper()
        return f"{city}, {state}", state, city

    # 3) Lookup by locality name from reference mapper (highest-frequency state).
    state = LOCALITY_STATE_MAP.get(normalized_label)
    if state in STATE_CODES:
        return f"{normalized_label}, {state}", state, normalized_label

    # 4) Ambiguous locality in mapper (top-count tie across states).
    # Keep unresolved so output doesn't silently assign wrong state.
    if normalized_label in LOCALITY_AMBIGUOUS_MAP:
        return normalized_label, pd.NA, normalized_label

    # last-resort fallback (uppercase)
    return normalized_label, pd.NA, normalized_label


def is_location_mapped(raw_label: str) -> bool:
    """True when raw label resolves to a known state."""
    return pd.notna(normalize_location(raw_label)[1])


def is_location_ambiguous(raw_label: str) -> bool:
    """True when raw label has a top-count tie across multiple states."""
    return clean_text(raw_label).upper() in LOCALITY_AMBIGUOUS_MAP

In [5]:
def parse_matrix_to_wide(path, sheet=0, debug=True):
    """Parse cross-matrix from Excel and return wide-format DataFrame."""
    raw = pd.read_excel(path, sheet_name=sheet, header=None)

    if debug:
        print("raw shape:", raw.shape)

    txt = raw.copy()
    for c in txt.columns:
        txt[c] = txt[c].astype(str).str.strip()

    records = []

    for section_name, metric in SECTION_TO_COL.items():
        section_hits = (txt == section_name).any(axis=1)
        if not section_hits.any():
            if debug:
                print(f"[WARN] section not found: {section_name}")
            continue

        srow = section_hits[section_hits].index[0]

        # In your sheet, destination headers are on SAME row as section label.
        header_cols_same_row = [c for c in range(1, raw.shape[1]) if is_text_label(raw.iat[srow, c])]
        if len(header_cols_same_row) >= 1:  # Support matrices with 1+ destinations
            hrow = srow
            valid_header_cols = header_cols_same_row
        else:
            # Fallback for other formats
            hrow = srow + 1
            valid_header_cols = [c for c in range(1, raw.shape[1]) if is_text_label(raw.iat[hrow, c])]

        if not valid_header_cols:
            if debug:
                print(f"[WARN] no destination headers for section: {section_name}")
            continue

        if debug:
            print(f"{section_name}: section_row={srow}, header_row={hrow}, destinations={len(valid_header_cols)}")

        # Data starts after header row
        r = hrow + 1
        while r < len(raw):
            row_text = " ".join(str(v).strip().upper() for v in raw.iloc[r].tolist() if pd.notna(v))
            if any(sec in row_text for sec in SECTION_TO_COL.keys()):
                break

            # Stop when a different table header starts (e.g. HEAVY COMMERCIAL)
            first_cell = raw.iat[r, 0]
            text_cells_in_row = sum(is_text_label(raw.iat[r, c]) for c in range(raw.shape[1]))
            if is_text_label(first_cell) and text_cells_in_row >= 3:
                break

            from_cell = raw.iat[r, 0]
            if pd.notna(from_cell) and str(from_cell).strip() != "":
                from_raw = clean_text(from_cell)

                for c in valid_header_cols:
                    to_cell = raw.iat[hrow, c]
                    val = parse_money(raw.iat[r, c])

                    if is_text_label(to_cell) and val is not None:
                        records.append({
                            "from_raw": from_raw,
                            "to_raw": clean_text(to_cell),
                            "metric": metric,
                            "value": val,
                        })
            r += 1

    if not records:
        raise ValueError("No records parsed. Check FILE_PATH/SHEET_NAME and Excel layout.")

    long_df = pd.DataFrame(records)

    wide = (
        long_df
        .pivot_table(
            index=["from_raw", "to_raw"],
            columns="metric",
            values="value",
            aggfunc="first"
        )
        .reset_index()
    )
    wide.columns.name = None

    # Ensure both columns exist
    for col in ["pass", "lcv"]:
        if col not in wide.columns:
            wide[col] = pd.NA

    # clean text/newlines
    for col in ["from_raw", "to_raw"]:
        wide[col] = wide[col].astype(str).apply(clean_text)

    return wide.reset_index(drop=True)

In [6]:
def build_target_schema(wide_df, carrier):
    """Convert wide DataFrame to target output schema (all location/carrier columns uppercase)."""
    out = wide_df.copy()

    # Filter out rows where pass or lcv is NaN
    out = out.dropna(subset=["pass", "lcv"], how="any")

    from_norm = out["from_raw"].apply(normalize_location)
    to_norm = out["to_raw"].apply(normalize_location)

    out["from"] = from_norm.apply(lambda x: x[0])
    out["from_state"] = from_norm.apply(lambda x: x[1])
    out["from_loc"] = from_norm.apply(lambda x: x[2])

    out["to"] = to_norm.apply(lambda x: x[0])
    out["to_state"] = to_norm.apply(lambda x: x[1])
    out["to_loc"] = to_norm.apply(lambda x: x[2])

    out["carrier"] = carrier.upper()
    out["tab"] = "hub"
    out["carrier_type"] = "hub"
    out["transit"] = pd.NA

    # Split into same-origin and different-origin
    same_origin = out[out["from"] == out["to"]].copy()
    diff_origin = out[out["from"] != out["to"]].copy()

    # Different origin: depot-depot (single record)
    diff_origin["type"] = "depot-depot"

    # Same origin: create depot-door and door-depot records
    if not same_origin.empty:
        depot_door = same_origin.copy()
        depot_door["type"] = "depot-door"

        door_depot = same_origin.copy()
        door_depot["type"] = "door-depot"

        same_origin_records = pd.concat([depot_door, door_depot], ignore_index=True)
    else:
        same_origin_records = pd.DataFrame()

    # Combine all records
    final = pd.concat([diff_origin, same_origin_records], ignore_index=True)

    return final[
        [
            "from", "to", "from_state", "to_state",
            "pass", "lcv",
            "type", "carrier", "tab", "carrier_type", "transit",
            "from_loc", "to_loc",
        ]
    ]

In [7]:
def get_sheet_names(path):
    """Return list of all sheet names in workbook."""
    xl = pd.ExcelFile(path)
    return xl.sheet_names


def print_unmapped_labels(wide_df):
    """Print labels that cannot be resolved by overrides or locality mapper."""
    labels = set(wide_df["from_raw"]) | set(wide_df["to_raw"])
    ambiguous = sorted([x for x in labels if is_location_ambiguous(x)])
    unresolved = sorted([x for x in labels if not is_location_mapped(x) and not is_location_ambiguous(x)])

    if ambiguous:
        print("\n[WARN] Ambiguous localities (top-count tie across states; add manual override):")
        for label in ambiguous:
            states = ", ".join(LOCALITY_AMBIGUOUS_MAP.get(clean_text(label).upper(), []))
            print(f"  - {label}: {states}")

    if unresolved:
        print("\n[WARN] Unresolved labels (add manual override or mapper row):")
        for label in unresolved:
            print(f"  - {label}")

    if not ambiguous and not unresolved:
        print("\n[INFO] All labels mapped.")

In [8]:
def parse_all_sheets(path, debug=True):
    """Parse all sheets and return dictionary keyed by sheet name."""
    sheet_names = get_sheet_names(path)
    results = {}
    unmapped_carriers = []

    for sheet_name in sheet_names:
        if debug:
            print(f"\n{'='*50}")
            print(f"Processing sheet: {sheet_name}")
            print('='*50)

        try:
            wide = parse_matrix_to_wide(path, sheet=sheet_name, debug=debug)

            # Get carrier for this sheet
            carrier = get_carrier_from_sheet_name(sheet_name)
            if carrier == DEFAULT_CARRIER:
                unmapped_carriers.append(sheet_name)
                if debug:
                    print(f"[WARN] Carrier: {carrier} (unmapped - add pattern to CARRIER_PATTERNS)")
            else:
                if debug:
                    print(f"[INFO] Carrier: {carrier}")

            final_df = build_target_schema(wide, carrier=carrier)
            results[sheet_name] = final_df

            if debug:
                print(f"[OK] {sheet_name}: {len(final_df)} rows")
                print_unmapped_labels(wide)
        except Exception as e:
            if debug:
                print(f"[SKIP] {sheet_name}: {e}")
            continue

    # Final summary of unmapped carriers
    if unmapped_carriers and debug:
        print(f"\n{'='*50}")
        print(f"[WARN] UNMAPPED CARRIERS SUMMARY")
        print('='*50)
        print(f"The following sheets could not be mapped to a carrier:")
        for sheet in unmapped_carriers:
            print(f"  - {sheet}")
        print(f"\nAdd patterns to CARRIER_PATTERNS to map these sheets.")

    return results

In [9]:
# =========================
# RUN - Parse All Sheets
# =========================
all_sheets = parse_all_sheets(FILE_PATH, debug=True)

print(f"\n{'='*50}")
print(f"SUMMARY: Parsed {len(all_sheets)} sheets")
print('='*50)

unmapped_carriers = []
for sheet_name, df in all_sheets.items():
    carrier = df['carrier'].iloc[0]
    print(f"  - {sheet_name}: {len(df)} rows (carrier: {carrier})")
    if carrier == DEFAULT_CARRIER:
        unmapped_carriers.append(sheet_name)

# Final warning about unmapped carriers
if unmapped_carriers:
    print(f"\n[WARN] Sheets with unmapped carrier (using '{DEFAULT_CARRIER}'):")
    for sheet in unmapped_carriers:
        print(f"  - {sheet}")
    print("\nAdd patterns to CARRIER_PATTERNS to map these sheets.")
else:
    print("\n[INFO] All sheets mapped to a carrier.")

==================================================
Processing sheet: Autocare Rate Matrix 14012026
==================================================
raw shape: (48, 14)
SEDAN: section_row=4, header_row=4, destinations=13
SUV / LIGHT COMMERCIAL: section_row=19, header_row=19, destinations=13
[INFO] Carrier: Autocare
[OK] Autocare Rate Matrix 14012026: 156 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Shipping
==================================================
raw shape: (35, 11)
SEDAN: section_row=1, header_row=1, destinations=10
SUV / LIGHT COMMERCIAL: section_row=11, header_row=11, destinations=10
[INFO] Carrier: Shipping
[OK] Shipping: 11 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Automover
==================================================
raw shape: (27, 6)
SEDAN: section_row=1, header_row=1, destinations=5
SUV / LIGHT COMMERCIAL: section_row=7, header_row=7, destinations=5
[INFO] Carrier: Automover
[OK] Automover: 11 rows

[INFO] All labels mapped.

==================================================
Processing sheet: A1
==================================================
raw shape: (25, 4)
SEDAN: section_row=1, header_row=1, destinations=3
SUV / LIGHT COMMERCIAL: section_row=6, header_row=6, destinations=3
[INFO] Carrier: A1
[OK] A1: 6 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Hunter United
==================================================
raw shape: (30, 6)
SEDAN: section_row=1, header_row=1, destinations=5
SUV / LIGHT COMMERCIAL: section_row=8, header_row=8, destinations=5
[INFO] Carrier: Hunter United
[OK] Hunter United: 10 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Carways
==================================================
raw shape: (31, 7)
SEDAN: section_row=1, header_row=1, destinations=6
SUV / LIGHT COMMERCIAL: section_row=9, header_row=9, destinations=6
[INFO] Carrier: Carways
[OK] Carways: 18 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Ace Car Carriers
==================================================
raw shape: (9, 2)
SEDAN: section_row=1, header_row=1, destinations=1
SUV / LIGHT COMMERCIAL: section_row=4, header_row=4, destinations=1
[INFO] Carrier: Ace Car Carriers
[OK] Ace Car Carriers: 2 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Alfies Towing
==================================================
raw shape: (9, 2)
SEDAN: section_row=1, header_row=1, destinations=1
SUV / LIGHT COMMERCIAL: section_row=4, header_row=4, destinations=1
[INFO] Carrier: Alfies Towing
[OK] Alfies Towing: 2 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Haul Car
==================================================
raw shape: (11, 3)
SEDAN: section_row=1, header_row=1, destinations=2
SUV / LIGHT COMMERCIAL: section_row=5, header_row=5, destinations=2
[INFO] Carrier: Haul Car
[OK] Haul Car: 2 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Cairns Car Carriers
==================================================
raw shape: (11, 3)
SEDAN: section_row=1, header_row=1, destinations=2
SUV / LIGHT COMMERCIAL: section_row=5, header_row=5, destinations=2
[INFO] Carrier: Cairns Car Carriers
[OK] Cairns Car Carriers: 2 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Melcrest
==================================================
raw shape: (33, 9)
SEDAN: section_row=1, header_row=1, destinations=8
SUV / LIGHT COMMERCIAL: section_row=10, header_row=10, destinations=8
[INFO] Carrier: Melcrest
[OK] Melcrest: 42 rows

[INFO] All labels mapped.

==================================================
Processing sheet: SMB
==================================================
raw shape: (35, 12)
SEDAN: section_row=2, header_row=2, destinations=11
SUV / LIGHT COMMERCIAL: section_row=15, header_row=15, destinations=7
[INFO] Carrier: SMB
[OK] SMB: 57 rows

[INFO] All labels mapped.

==================================================
Processing sheet: IAT Transport
==================================================
raw shape: (27, 8)
SEDAN: section_row=2, header_row=2, destinations=7
SUV / LIGHT COMMERCIAL: section_row=11, header_row=11, destinations=7
[INFO] Carrier: IAT Transport
[OK] IAT Transport: 18 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Mackay Car & Commercial
==================================================
raw shape: (15, 2)
SEDAN: section_row=2, header_row=2, destinations=1
SUV / LIGHT COMMERCIAL: section_row=5, header_row=5, destinations=1
[INFO] Carrier: Mackay Car & Commercial
[OK] Mackay Car & Commercial: 2 rows

[INFO] All labels mapped.

==================================================
Processing sheet: GTTKAL
==================================================
raw shape: (17, 3)
SEDAN: section_row=2, header_row=2, destinations=2
SUV / LIGHT COMMERCIAL: section_row=6, header_row=6, destinations=2
[INFO] Carrier: GTTKAL
[OK] GTTKAL: 4 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Capital Towing
==================================================
raw shape: (15, 2)
SEDAN: section_row=2, header_row=2, destinations=1
SUV / LIGHT COMMERCIAL: section_row=5, header_row=5, destinations=1
[INFO] Carrier: Capital Towing
[OK] Capital Towing: 2 rows

[INFO] All labels mapped.

==================================================
Processing sheet: Newcastle Vehicle Transporters
==================================================
raw shape: (8, 3)
SEDAN: section_row=1, header_row=1, destinations=2
SUV / LIGHT COMMERCIAL: section_row=5, header_row=5, destinations=2
[INFO] Carrier: Newcastle Vehicle Transporters
[OK] Newcastle Vehicle Transporters: 2 rows

[INFO] All labels mapped.

==================================================
SUMMARY: Parsed 17 sheets
==================================================
  - Autocare Rate Matrix 14012026: 156 rows (carrier: AUTOCARE)
  - Shipping: 11 rows (carrier: SHIPPING)
  - Automover: 11 rows (carrier: AUTOMOVER)
  - A1: 6 rows (carrier: A1)
  - Hunter United: 10 rows (carrier: HUNTER UNITED)
  - Carways: 18 rows (carrier: CARWAYS)
  - Ace Car Carriers: 2 rows (carrier: ACE CAR CARRIERS)
  - Alfies Towing: 2 rows (carrier: ALFIES TOWING)
  - Haul Car: 2 rows (carrier: HAUL CAR)
  - Cairns Car Carriers: 2 rows (carrier: CAIRNS CAR CARRIERS)
  - Melcrest: 42 rows (carrier: MELCREST)
  - SMB: 57 rows (carrier: SMB)
  - IAT Transport: 18 rows (carrier: IAT TRANSPORT)
  - Mackay Car & Commercial: 2 rows (carrier: MACKAY CAR & COMMERCIAL)
  - GTTKAL: 4 rows (carrier: GTTKAL)
  - Capital Towing: 2 rows (carrier: CAPITAL TOWING)
  - Newcastle Vehicle Transporters: 2 rows (carrier: NEWCASTLE VEHICLE TRANSPORTERS)

[INFO] All sheets mapped to a carrier.

In [10]:
# =========================
# PREVIEW - Display each sheet
# =========================
for sheet_name, df in all_sheets.items():
    print(f"\n{'='*50}")
    print(f"Sheet: {sheet_name}")
    print('='*50)
    display(df.head(10))

==================================================
Sheet: Autocare Rate Matrix 14012026
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"ADELAIDE, SA","ALICE SPRINGS, NT",SA,NT,950.0,1187.50,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,ALICE SPRINGS
1,"ADELAIDE, SA","BRISBANE, QLD",SA,QLD,1029.0,1286.25,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,BRISBANE
2,"ADELAIDE, SA","CAIRNS, QLD",SA,QLD,1856.0,2320.00,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,CAIRNS
3,"ADELAIDE, SA","DARWIN, NT",SA,NT,1060.8,1644.24,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,DARWIN
4,"ADELAIDE, SA","DEVONPORT, TAS",SA,TAS,728.8,911.00,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,DEVONPORT
5,"ADELAIDE, SA","HOBART, TAS",SA,TAS,1126.0,1407.50,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,HOBART
6,"ADELAIDE, SA","MELBOURNE, VIC",SA,VIC,218.4,273.00,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,MELBOURNE
7,"ADELAIDE, SA","MT ISA, QLD",SA,QLD,2321.0,2901.25,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,MT ISA
8,"ADELAIDE, SA","PERTH, WA",SA,WA,838.0,1047.50,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,PERTH
9,"ADELAIDE, SA","SYDNEY, NSW",SA,NSW,680.0,850.00,depot-depot,AUTOCARE,hub,hub,<NA>,ADELAIDE,SYDNEY

==================================================
Sheet: Shipping
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"ADELAIDE, SA","PERTH, WA",SA,WA,1227.27,1318.18,depot-depot,SHIPPING,hub,hub,<NA>,ADELAIDE,PERTH
1,"BRISBANE, QLD","PERTH, WA",QLD,WA,1177.27,1268.18,depot-depot,SHIPPING,hub,hub,<NA>,BRISBANE,PERTH
2,"DEVONPORT, TAS","PERTH, WA",TAS,WA,1749.79,1799.79,depot-depot,SHIPPING,hub,hub,<NA>,DEVONPORT,PERTH
3,"HOBART, TAS","PERTH, WA",TAS,WA,1765.88,1815.88,depot-depot,SHIPPING,hub,hub,<NA>,HOBART,PERTH
4,"MELBOURNE, VIC","PERTH, WA",VIC,WA,1230.00,1318.18,depot-depot,SHIPPING,hub,hub,<NA>,MELBOURNE,PERTH
5,"PERTH, WA","BRISBANE, QLD",WA,QLD,1341.73,1441.73,depot-depot,SHIPPING,hub,hub,<NA>,PERTH,BRISBANE
6,"PERTH, WA","MELBOURNE, VIC",WA,VIC,1073.70,1173.70,depot-depot,SHIPPING,hub,hub,<NA>,PERTH,MELBOURNE
7,"PERTH, WA","SYDNEY, NSW",WA,NSW,1204.42,1304.42,depot-depot,SHIPPING,hub,hub,<NA>,PERTH,SYDNEY
8,"PERTH, WA","WOLLONGONG, NSW",WA,NSW,1100.00,1200.00,depot-depot,SHIPPING,hub,hub,<NA>,PERTH,WOLLONGONG
9,"SYDNEY, NSW","PERTH, WA",NSW,WA,1279.16,1329.13,depot-depot,SHIPPING,hub,hub,<NA>,SYDNEY,PERTH

==================================================
Sheet: Automover
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"BRISBANE, QLD","MELBOURNE, VIC",QLD,VIC,313.0,452.0,depot-depot,AUTOMOVER,hub,hub,<NA>,BRISBANE,MELBOURNE
1,"BRISBANE, QLD","PERTH, WA",QLD,WA,1060.0,1457.0,depot-depot,AUTOMOVER,hub,hub,<NA>,BRISBANE,PERTH
2,"BRISBANE, QLD","SYDNEY, NSW",QLD,NSW,455.0,600.0,depot-depot,AUTOMOVER,hub,hub,<NA>,BRISBANE,SYDNEY
3,"MELBOURNE, VIC","BRISBANE, QLD",VIC,QLD,434.0,723.0,depot-depot,AUTOMOVER,hub,hub,<NA>,MELBOURNE,BRISBANE
4,"MELBOURNE, VIC","PERTH, WA",VIC,WA,1060.0,1457.0,depot-depot,AUTOMOVER,hub,hub,<NA>,MELBOURNE,PERTH
5,"PERTH, WA","BRISBANE, QLD",WA,QLD,843.0,1024.0,depot-depot,AUTOMOVER,hub,hub,<NA>,PERTH,BRISBANE
6,"PERTH, WA","MELBOURNE, VIC",WA,VIC,800.0,1000.0,depot-depot,AUTOMOVER,hub,hub,<NA>,PERTH,MELBOURNE
7,"PERTH, WA","SYDNEY, NSW",WA,NSW,843.0,1024.0,depot-depot,AUTOMOVER,hub,hub,<NA>,PERTH,SYDNEY
8,"PERTH, WA","TOWNSVILLE, QLD",WA,QLD,2000.0,2300.0,depot-depot,AUTOMOVER,hub,hub,<NA>,PERTH,TOWNSVILLE
9,"SYDNEY, NSW","BRISBANE, QLD",NSW,QLD,700.0,800.0,depot-depot,AUTOMOVER,hub,hub,<NA>,SYDNEY,BRISBANE

==================================================
Sheet: A1
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"BRISBANE, QLD","MELBOURNE, VIC",QLD,VIC,390.0,621.00,depot-depot,A1,hub,hub,<NA>,BRISBANE,MELBOURNE
1,"BRISBANE, QLD","SYDNEY, NSW",QLD,NSW,275.0,436.36,depot-depot,A1,hub,hub,<NA>,BRISBANE,SYDNEY
2,"MELBOURNE, VIC","BRISBANE, QLD",VIC,QLD,557.0,900.00,depot-depot,A1,hub,hub,<NA>,MELBOURNE,BRISBANE
3,"MELBOURNE, VIC","SYDNEY, NSW",VIC,NSW,400.0,500.00,depot-depot,A1,hub,hub,<NA>,MELBOURNE,SYDNEY
4,"SYDNEY, NSW","BRISBANE, QLD",NSW,QLD,358.0,545.00,depot-depot,A1,hub,hub,<NA>,SYDNEY,BRISBANE
5,"SYDNEY, NSW","MELBOURNE, VIC",NSW,VIC,265.0,318.00,depot-depot,A1,hub,hub,<NA>,SYDNEY,MELBOURNE

==================================================
Sheet: Hunter United
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"BRISBANE, QLD","NEWCASTLE, NSW",QLD,NSW,713.63,713.63,depot-depot,HUNTER UNITED,hub,hub,<NA>,BRISBANE,NEWCASTLE
1,"MELBOURNE, VIC","NEWCASTLE, NSW",VIC,NSW,713.63,713.63,depot-depot,HUNTER UNITED,hub,hub,<NA>,MELBOURNE,NEWCASTLE
2,"MELBOURNE, VIC","SYDNEY, NSW",VIC,NSW,713.63,713.63,depot-depot,HUNTER UNITED,hub,hub,<NA>,MELBOURNE,SYDNEY
3,"NEWCASTLE, NSW","BRISBANE, QLD",NSW,QLD,713.63,713.63,depot-depot,HUNTER UNITED,hub,hub,<NA>,NEWCASTLE,BRISBANE
4,"NEWCASTLE, NSW","MELBOURNE, VIC",NSW,VIC,713.63,713.63,depot-depot,HUNTER UNITED,hub,hub,<NA>,NEWCASTLE,MELBOURNE
5,"NEWCASTLE, NSW","SYDNEY, NSW",NSW,NSW,259.09,259.09,depot-depot,HUNTER UNITED,hub,hub,<NA>,NEWCASTLE,SYDNEY
6,"NEWCASTLE, NSW","WOLLONGONG, NSW",NSW,NSW,600.00,600.00,depot-depot,HUNTER UNITED,hub,hub,<NA>,NEWCASTLE,WOLLONGONG
7,"SYDNEY, NSW","NEWCASTLE, NSW",NSW,NSW,259.09,259.09,depot-depot,HUNTER UNITED,hub,hub,<NA>,SYDNEY,NEWCASTLE
8,"NEWCASTLE, NSW","NEWCASTLE, NSW",NSW,NSW,259.09,259.09,depot-door,HUNTER UNITED,hub,hub,<NA>,NEWCASTLE,NEWCASTLE
9,"NEWCASTLE, NSW","NEWCASTLE, NSW",NSW,NSW,259.09,259.09,door-depot,HUNTER UNITED,hub,hub,<NA>,NEWCASTLE,NEWCASTLE

==================================================
Sheet: Carways
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"ADELAIDE, SA","BRISBANE, QLD",SA,QLD,1627.50,1732.50,depot-depot,CARWAYS,hub,hub,<NA>,ADELAIDE,BRISBANE
1,"ADELAIDE, SA","MELBOURNE, VIC",SA,VIC,630.00,735.00,depot-depot,CARWAYS,hub,hub,<NA>,ADELAIDE,MELBOURNE
2,"ADELAIDE, SA","SYDNEY, NSW",SA,NSW,1050.00,1155.00,depot-depot,CARWAYS,hub,hub,<NA>,ADELAIDE,SYDNEY
3,"BRISBANE, QLD","ADELAIDE, SA",QLD,SA,1417.50,1522.50,depot-depot,CARWAYS,hub,hub,<NA>,BRISBANE,ADELAIDE
4,"BRISBANE, QLD","CAIRNS, QLD",QLD,QLD,770.29,770.29,depot-depot,CARWAYS,hub,hub,<NA>,BRISBANE,CAIRNS
5,"BRISBANE, QLD","MELBOURNE, VIC",QLD,VIC,840.00,892.50,depot-depot,CARWAYS,hub,hub,<NA>,BRISBANE,MELBOURNE
6,"BRISBANE, QLD","SYDNEY, NSW",QLD,NSW,472.50,557.50,depot-depot,CARWAYS,hub,hub,<NA>,BRISBANE,SYDNEY
7,"BRISBANE, QLD","TOWNSVILLE, QLD",QLD,QLD,798.00,798.00,depot-depot,CARWAYS,hub,hub,<NA>,BRISBANE,TOWNSVILLE
8,"CAIRNS, QLD","BRISBANE, QLD",QLD,QLD,674.61,674.61,depot-depot,CARWAYS,hub,hub,<NA>,CAIRNS,BRISBANE
9,"MELBOURNE, VIC","ADELAIDE, SA",VIC,SA,787.50,1102.50,depot-depot,CARWAYS,hub,hub,<NA>,MELBOURNE,ADELAIDE

==================================================
Sheet: Ace Car Carriers
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"MELBOURNE, VIC","MELBOURNE, VIC",VIC,VIC,200.0,200.0,depot-door,ACE CAR CARRIERS,hub,hub,<NA>,MELBOURNE,MELBOURNE
1,"MELBOURNE, VIC","MELBOURNE, VIC",VIC,VIC,200.0,200.0,door-depot,ACE CAR CARRIERS,hub,hub,<NA>,MELBOURNE,MELBOURNE

==================================================
Sheet: Alfies Towing
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"CAIRNS, QLD","CAIRNS, QLD",QLD,QLD,120.0,120.0,depot-door,ALFIES TOWING,hub,hub,<NA>,CAIRNS,CAIRNS
1,"CAIRNS, QLD","CAIRNS, QLD",QLD,QLD,120.0,120.0,door-depot,ALFIES TOWING,hub,hub,<NA>,CAIRNS,CAIRNS

==================================================
Sheet: Haul Car
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"ADELAIDE, SA","BRISBANE, QLD",SA,QLD,745.45,977.27,depot-depot,HAUL CAR,hub,hub,<NA>,ADELAIDE,BRISBANE
1,"BRISBANE, QLD","ADELAIDE, SA",QLD,SA,745.45,977.27,depot-depot,HAUL CAR,hub,hub,<NA>,BRISBANE,ADELAIDE

==================================================
Sheet: Cairns Car Carriers
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"CAIRNS, QLD","TOWNSVILLE, QLD",QLD,QLD,300.0,300.0,depot-depot,CAIRNS CAR CARRIERS,hub,hub,<NA>,CAIRNS,TOWNSVILLE
1,"TOWNSVILLE, QLD","CAIRNS, QLD",QLD,QLD,300.0,300.0,depot-depot,CAIRNS CAR CARRIERS,hub,hub,<NA>,TOWNSVILLE,CAIRNS

==================================================
Sheet: Melcrest
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"BRISBANE, QLD","ADELAIDE, SA",QLD,SA,719.70,833.33,depot-depot,MELCREST,hub,hub,<NA>,BRISBANE,ADELAIDE
1,"BRISBANE, QLD","CAIRNS, QLD",QLD,QLD,844.70,1034.09,depot-depot,MELCREST,hub,hub,<NA>,BRISBANE,CAIRNS
2,"BRISBANE, QLD","DARWIN, NT",QLD,NT,1454.54,1863.63,depot-depot,MELCREST,hub,hub,<NA>,BRISBANE,DARWIN
3,"BRISBANE, QLD","MACKAY, QLD",QLD,QLD,556.82,659.09,depot-depot,MELCREST,hub,hub,<NA>,BRISBANE,MACKAY
4,"BRISBANE, QLD","MT ISA, QLD",QLD,QLD,1053.03,1295.45,depot-depot,MELCREST,hub,hub,<NA>,BRISBANE,MT ISA
5,"BRISBANE, QLD","ROCKHAMPTON, QLD",QLD,QLD,424.24,537.88,depot-depot,MELCREST,hub,hub,<NA>,BRISBANE,ROCKHAMPTON
6,"BRISBANE, QLD","TOWNSVILLE, QLD",QLD,QLD,704.55,871.21,depot-depot,MELCREST,hub,hub,<NA>,BRISBANE,TOWNSVILLE
7,"CAIRNS, QLD","BRISBANE, QLD",QLD,QLD,477.27,477.27,depot-depot,MELCREST,hub,hub,<NA>,CAIRNS,BRISBANE
8,"CAIRNS, QLD","DARWIN, NT",QLD,NT,1856.06,1856.06,depot-depot,MELCREST,hub,hub,<NA>,CAIRNS,DARWIN
9,"CAIRNS, QLD","MACKAY, QLD",QLD,QLD,375.00,375.00,depot-depot,MELCREST,hub,hub,<NA>,CAIRNS,MACKAY

==================================================
Sheet: SMB
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"ADELAIDE, SA","ALICE SPRINGS, NT",SA,NT,909.09,1409.09,depot-depot,SMB,hub,hub,<NA>,ADELAIDE,ALICE SPRINGS
1,"ADELAIDE, SA","BRISBANE, QLD",SA,QLD,618.18,736.36,depot-depot,SMB,hub,hub,<NA>,ADELAIDE,BRISBANE
2,"ADELAIDE, SA","DARWIN, NT",SA,NT,909.09,1363.63,depot-depot,SMB,hub,hub,<NA>,ADELAIDE,DARWIN
3,"ADELAIDE, SA","MELBOURNE, VIC",SA,VIC,205.05,272.73,depot-depot,SMB,hub,hub,<NA>,ADELAIDE,MELBOURNE
4,"ADELAIDE, SA","PERTH, WA",SA,WA,745.45,1227.27,depot-depot,SMB,hub,hub,<NA>,ADELAIDE,PERTH
5,"ADELAIDE, SA","SYDNEY, NSW",SA,NSW,445.55,581.82,depot-depot,SMB,hub,hub,<NA>,ADELAIDE,SYDNEY
6,"ALICE SPRINGS, NT","ADELAIDE, SA",NT,SA,500.00,727.27,depot-depot,SMB,hub,hub,<NA>,ALICE SPRINGS,ADELAIDE
7,"ALICE SPRINGS, NT","BRISBANE, QLD",NT,QLD,1227.27,1409.09,depot-depot,SMB,hub,hub,<NA>,ALICE SPRINGS,BRISBANE
8,"ALICE SPRINGS, NT","DARWIN, NT",NT,NT,436.36,590.91,depot-depot,SMB,hub,hub,<NA>,ALICE SPRINGS,DARWIN
9,"ALICE SPRINGS, NT","MELBOURNE, VIC",NT,VIC,773.73,900.00,depot-depot,SMB,hub,hub,<NA>,ALICE SPRINGS,MELBOURNE

==================================================
Sheet: IAT Transport
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"SUNSHINE COAST, QLD","BUNDABERG, QLD",QLD,QLD,370.0,370.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,BUNDABERG
1,"SUNSHINE COAST, QLD","CAIRNS, QLD",QLD,QLD,1000.0,1000.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,CAIRNS
2,"SUNSHINE COAST, QLD","MACKAY, QLD",QLD,QLD,690.0,690.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,MACKAY
3,"SUNSHINE COAST, QLD","MARYBOROUGH, QLD",QLD,QLD,315.0,315.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,MARYBOROUGH
4,"SUNSHINE COAST, QLD","TOWNSVILLE, QLD",QLD,QLD,750.0,750.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,TOWNSVILLE
5,"SUNSHINE COAST, QLD","BUNDABERG, QLD",QLD,QLD,370.0,370.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,BUNDABERG
6,"SUNSHINE COAST, QLD","CAIRNS, QLD",QLD,QLD,1000.0,1000.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,CAIRNS
7,"SUNSHINE COAST, QLD","MACKAY, QLD",QLD,QLD,690.0,690.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,MACKAY
8,"SUNSHINE COAST, QLD","MARYBOROUGH, QLD",QLD,QLD,315.0,315.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,MARYBOROUGH
9,"SUNSHINE COAST, QLD","TOWNSVILLE, QLD",QLD,QLD,750.0,750.0,depot-depot,IAT TRANSPORT,hub,hub,<NA>,SUNSHINE COAST,TOWNSVILLE

==================================================
Sheet: Mackay Car & Commercial
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"MACKAY, QLD","MACKAY, QLD",QLD,QLD,240.0,240.0,depot-door,MACKAY CAR & COMMERCIAL,hub,hub,<NA>,MACKAY,MACKAY
1,"MACKAY, QLD","MACKAY, QLD",QLD,QLD,240.0,240.0,door-depot,MACKAY CAR & COMMERCIAL,hub,hub,<NA>,MACKAY,MACKAY

==================================================
Sheet: GTTKAL
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"KALGOORLIE, WA","PERTH, WA",WA,WA,3422.1,3422.1,depot-depot,GTTKAL,hub,hub,<NA>,KALGOORLIE,PERTH
1,"PERTH, WA","KALGOORLIE, WA",WA,WA,3422.1,3442.1,depot-depot,GTTKAL,hub,hub,<NA>,PERTH,KALGOORLIE
2,"KALGOORLIE, WA","KALGOORLIE, WA",WA,WA,195.2,195.2,depot-door,GTTKAL,hub,hub,<NA>,KALGOORLIE,KALGOORLIE
3,"KALGOORLIE, WA","KALGOORLIE, WA",WA,WA,195.2,195.2,door-depot,GTTKAL,hub,hub,<NA>,KALGOORLIE,KALGOORLIE

==================================================
Sheet: Capital Towing
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"CANBERRA, ACT","CANBERRA, ACT",ACT,ACT,100.0,100.0,depot-door,CAPITAL TOWING,hub,hub,<NA>,CANBERRA,CANBERRA
1,"CANBERRA, ACT","CANBERRA, ACT",ACT,ACT,100.0,100.0,door-depot,CAPITAL TOWING,hub,hub,<NA>,CANBERRA,CANBERRA

==================================================
Sheet: Newcastle Vehicle Transporters
==================================================

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"NEWCASTLE, NSW","SYDNEY, NSW",NSW,NSW,400.0,500.0,depot-depot,NEWCASTLE VEHICLE TRANSPORTERS,hub,hub,<NA>,NEWCASTLE,SYDNEY
1,"SYDNEY, NSW","NEWCASTLE, NSW",NSW,NSW,400.0,500.0,depot-depot,NEWCASTLE VEHICLE TRANSPORTERS,hub,hub,<NA>,SYDNEY,NEWCASTLE

In [11]:
# =========================
# CONCATENATE ALL SHEETS INTO ONE DATAFRAME
# =========================
all_data = pd.concat(
    [df.assign(sheet=name) for name, df in all_sheets.items()],
    ignore_index=True
)

all_data['tab'] = 'new-template'
del(all_data['sheet'])

rate_value_cols = ["pass", "lcv"]
numeric_rates = all_data[rate_value_cols].apply(pd.to_numeric, errors="coerce")
numeric_rates = numeric_rates.mask(numeric_rates.isin([float("inf"), float("-inf")]))
valid_rate_rows = numeric_rates.notna().all(axis=1) & numeric_rates.ne(0).all(axis=1)
dropped_rate_rows = len(all_data) - int(valid_rate_rows.sum())

all_data = all_data.loc[valid_rate_rows].copy()
for col in rate_value_cols:
    all_data[col] = numeric_rates.loc[valid_rate_rows, col]
all_data = all_data.reset_index(drop=True)

# Infer missing states from unique locality->state observations in this run.
state_pairs = pd.concat(
    [
        all_data[["from_loc", "from_state"]].rename(columns={"from_loc": "loc", "from_state": "state"}),
        all_data[["to_loc", "to_state"]].rename(columns={"to_loc": "loc", "to_state": "state"}),
    ],
    ignore_index=True,
)
state_pairs = state_pairs.dropna(subset=["loc", "state"]).copy()
state_pairs["loc"] = state_pairs["loc"].astype(str).str.strip().str.upper()
state_pairs["state"] = state_pairs["state"].astype(str).str.strip().str.upper()
state_pairs = state_pairs[state_pairs["state"].isin(STATE_CODES)]

unique_state_by_loc = (
    state_pairs.groupby("loc")["state"]
    .agg(lambda s: sorted(set(s)))
    .to_dict()
)
unique_state_by_loc = {
    loc: states[0]
    for loc, states in unique_state_by_loc.items()
    if len(states) == 1
}

missing_from_before = int(all_data["from_state"].isna().sum())
missing_to_before = int(all_data["to_state"].isna().sum())

all_data["from_state"] = all_data["from_state"].fillna(
    all_data["from_loc"].astype(str).str.strip().str.upper().map(unique_state_by_loc)
)
all_data["to_state"] = all_data["to_state"].fillna(
    all_data["to_loc"].astype(str).str.strip().str.upper().map(unique_state_by_loc)
)

all_data["from_state"] = all_data["from_state"].astype("string").str.strip().str.upper()
all_data["to_state"] = all_data["to_state"].astype("string").str.strip().str.upper()
all_data.loc[~all_data["from_state"].isin(STATE_CODES), "from_state"] = pd.NA
all_data.loc[~all_data["to_state"].isin(STATE_CODES), "to_state"] = pd.NA


def _append_state_if_missing(city_label, state_code):
    city_label = clean_text(city_label).upper()
    if pd.isna(state_code):
        return city_label
    if re.search(r",\s*[A-Z]{2,3}$", city_label):
        return city_label
    return f"{city_label}, {state_code}"


all_data["from"] = [
    _append_state_if_missing(city, state)
    for city, state in zip(all_data["from"], all_data["from_state"])
]
all_data["to"] = [
    _append_state_if_missing(city, state)
    for city, state in zip(all_data["to"], all_data["to_state"])
]

missing_from_after = int(all_data["from_state"].isna().sum())
missing_to_after = int(all_data["to_state"].isna().sum())

print(f"Total rows: {len(all_data)}")
if dropped_rate_rows:
    print(f"Dropped {dropped_rate_rows} rows with zero or non-numeric rate values.")
print(
    "Inferred missing states from unique locality evidence: "
    f"from_state {missing_from_before - missing_from_after}, "
    f"to_state {missing_to_before - missing_to_after}"
)
display(all_data)

if OUTPUT_CSV:
  all_data.to_csv(OUTPUT_CSV, index = False)

Total rows: 347

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"ADELAIDE, SA","ALICE SPRINGS, NT",SA,NT,950.0,1187.50,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,ALICE SPRINGS
1,"ADELAIDE, SA","BRISBANE, QLD",SA,QLD,1029.0,1286.25,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,BRISBANE
2,"ADELAIDE, SA","CAIRNS, QLD",SA,QLD,1856.0,2320.00,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,CAIRNS
3,"ADELAIDE, SA","DARWIN, NT",SA,NT,1060.8,1644.24,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,DARWIN
4,"ADELAIDE, SA","DEVONPORT, TAS",SA,TAS,728.8,911.00,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,DEVONPORT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,"KALGOORLIE, WA","KALGOORLIE, WA",WA,WA,195.2,195.20,door-depot,GTTKAL,new-template,hub,<NA>,KALGOORLIE,KALGOORLIE
343,"CANBERRA, ACT","CANBERRA, ACT",ACT,ACT,100.0,100.00,depot-door,CAPITAL TOWING,new-template,hub,<NA>,CANBERRA,CANBERRA
344,"CANBERRA, ACT","CANBERRA, ACT",ACT,ACT,100.0,100.00,door-depot,CAPITAL TOWING,new-template,hub,<NA>,CANBERRA,CANBERRA
345,"NEWCASTLE, NSW","SYDNEY, NSW",NSW,NSW,400.0,500.00,depot-depot,NEWCASTLE VEHICLE TRANSPORTERS,new-template,hub,<NA>,NEWCASTLE,SYDNEY
346,"SYDNEY, NSW","NEWCASTLE, NSW",NSW,NSW,400.0,500.00,depot-depot,NEWCASTLE VEHICLE TRANSPORTERS,new-template,hub,<NA>,SYDNEY,NEWCASTLE

In [12]:
all_data

,from,to,from_state,to_state,pass,lcv,type,carrier,tab,carrier_type,transit,from_loc,to_loc
0,"ADELAIDE, SA","ALICE SPRINGS, NT",SA,NT,950.0,1187.50,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,ALICE SPRINGS
1,"ADELAIDE, SA","BRISBANE, QLD",SA,QLD,1029.0,1286.25,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,BRISBANE
2,"ADELAIDE, SA","CAIRNS, QLD",SA,QLD,1856.0,2320.00,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,CAIRNS
3,"ADELAIDE, SA","DARWIN, NT",SA,NT,1060.8,1644.24,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,DARWIN
4,"ADELAIDE, SA","DEVONPORT, TAS",SA,TAS,728.8,911.00,depot-depot,AUTOCARE,new-template,hub,<NA>,ADELAIDE,DEVONPORT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,"KALGOORLIE, WA","KALGOORLIE, WA",WA,WA,195.2,195.20,door-depot,GTTKAL,new-template,hub,<NA>,KALGOORLIE,KALGOORLIE
343,"CANBERRA, ACT","CANBERRA, ACT",ACT,ACT,100.0,100.00,depot-door,CAPITAL TOWING,new-template,hub,<NA>,CANBERRA,CANBERRA
344,"CANBERRA, ACT","CANBERRA, ACT",ACT,ACT,100.0,100.00,door-depot,CAPITAL TOWING,new-template,hub,<NA>,CANBERRA,CANBERRA
345,"NEWCASTLE, NSW","SYDNEY, NSW",NSW,NSW,400.0,500.00,depot-depot,NEWCASTLE VEHICLE TRANSPORTERS,new-template,hub,<NA>,NEWCASTLE,SYDNEY
346,"SYDNEY, NSW","NEWCASTLE, NSW",NSW,NSW,400.0,500.00,depot-depot,NEWCASTLE VEHICLE TRANSPORTERS,new-template,hub,<NA>,SYDNEY,NEWCASTLE

In [13]:
# =========================
# FINAL TEXT REPORT (FULL)
# =========================
from datetime import datetime

errors = []
warnings = []

sheet_names = get_sheet_names(FILE_PATH)
parsed_sheet_names = set(all_sheets.keys())
skipped_sheets = [s for s in sheet_names if s not in parsed_sheet_names]

# Errors: sheets that failed parsing
for sheet_name in skipped_sheets:
    try:
        parse_matrix_to_wide(FILE_PATH, sheet=sheet_name, debug=False)
        errors.append(f"{sheet_name}: skipped unexpectedly")
    except Exception as e:
        errors.append(f"{sheet_name}: {e}")

# Warnings: unmapped carriers
unmapped_carrier_sheets = []
for sheet_name, df in all_sheets.items():
    if not df.empty and df['carrier'].iloc[0] == DEFAULT_CARRIER:
        unmapped_carrier_sheets.append(sheet_name)
if unmapped_carrier_sheets:
    warnings.append("Unmapped carrier sheets: " + ", ".join(sorted(unmapped_carrier_sheets)))

# Warnings: unresolved/ambiguous location labels
all_ambiguous_labels = {}
all_unresolved_labels = {}
for sheet_name in sorted(all_sheets.keys()):
    wide_df = parse_matrix_to_wide(FILE_PATH, sheet=sheet_name, debug=False)
    labels = set(wide_df['from_raw']) | set(wide_df['to_raw'])

    ambiguous = sorted([x for x in labels if is_location_ambiguous(x)])
    unresolved = sorted([x for x in labels if not is_location_mapped(x) and not is_location_ambiguous(x)])

    if ambiguous:
        all_ambiguous_labels[sheet_name] = ambiguous
    if unresolved:
        all_unresolved_labels[sheet_name] = unresolved

if all_ambiguous_labels:
    flat_ambiguous = sorted({label for labels in all_ambiguous_labels.values() for label in labels})
    warnings.append("Ambiguous location labels (state top-count tie): " + ", ".join(flat_ambiguous))
if all_unresolved_labels:
    flat_unresolved = sorted({label for labels in all_unresolved_labels.values() for label in labels})
    warnings.append("Unresolved location labels: " + ", ".join(flat_unresolved))

# Warnings: missing state values in final output
missing_from_state = int(all_data["from_state"].isna().sum())
missing_to_state = int(all_data["to_state"].isna().sum())
missing_state_mask = all_data["from_state"].isna() | all_data["to_state"].isna()
missing_state_rows = all_data.loc[
    missing_state_mask,
    ["carrier", "from", "to", "from_state", "to_state"],
].copy()
if not missing_state_rows.empty:
    warnings.append(
        "Rows with missing states: "
        f"{len(missing_state_rows)} "
        f"(missing from_state={missing_from_state}, missing to_state={missing_to_state})"
    )

# Carrier/rate tables
carrier_rates_df = all_data[["carrier", "from", "to", "pass", "lcv"]].copy()
carrier_rates_df = carrier_rates_df.sort_values(["carrier", "from", "to"]).reset_index(drop=True)

completeness_summary_df = (
    carrier_rates_df.groupby("carrier", dropna=False)
    .agg(
        routes=("carrier", "size"),
        missing_pass=("pass", lambda x: int(x.isna().sum())),
        missing_lcv=("lcv", lambda x: int(x.isna().sum())),
    )
    .reset_index()
    .sort_values("carrier")
)

# Numeric completeness (supported sections only)
section_numeric_total = 0
for sheet_name in sheet_names:
    raw_df = pd.read_excel(FILE_PATH, sheet_name=sheet_name, header=None)
    txt_df = raw_df.copy()
    for c in txt_df.columns:
        txt_df[c] = txt_df[c].astype(str).str.strip()

    for section_name in SECTION_TO_COL.keys():
        section_hits = (txt_df == section_name).any(axis=1)
        if not section_hits.any():
            continue

        srow = section_hits[section_hits].index[0]
        header_cols_same_row = [c for c in range(1, raw_df.shape[1]) if is_text_label(raw_df.iat[srow, c])]
        if len(header_cols_same_row) >= 1:
            hrow = srow
            valid_header_cols = header_cols_same_row
        else:
            hrow = srow + 1
            if hrow >= len(raw_df):
                continue
            valid_header_cols = [c for c in range(1, raw_df.shape[1]) if is_text_label(raw_df.iat[hrow, c])]

        if not valid_header_cols:
            continue

        r = hrow + 1
        while r < len(raw_df):
            row_text = " ".join(str(v).strip().upper() for v in raw_df.iloc[r].tolist() if pd.notna(v))
            if any(sec in row_text for sec in SECTION_TO_COL.keys()):
                break

            first_cell = raw_df.iat[r, 0]
            text_cells_in_row = sum(is_text_label(raw_df.iat[r, c]) for c in range(raw_df.shape[1]))
            if is_text_label(first_cell) and text_cells_in_row >= 3:
                break

            from_cell = raw_df.iat[r, 0]
            if pd.notna(from_cell) and str(from_cell).strip() != "":
                for c in valid_header_cols:
                    to_cell = raw_df.iat[hrow, c]
                    val = parse_money(raw_df.iat[r, c])
                    if is_text_label(to_cell) and val is not None:
                        section_numeric_total += 1
            r += 1

parsed_matrix_numeric_total = 0
for sheet_name in sorted(all_sheets.keys()):
    wide_df = parse_matrix_to_wide(FILE_PATH, sheet=sheet_name, debug=False)
    parsed_matrix_numeric_total += int(wide_df[["pass", "lcv"]].notna().sum().sum())

final_output_numeric_total = int(carrier_rates_df[["pass", "lcv"]].notna().sum().sum())

# Build full text report
line = "=" * 78
report_lines = []
report_lines.append(line)
report_lines.append("RATE IMPORT REPORT")
report_lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
report_lines.append(line)
report_lines.append(f"Workbook path: {FILE_PATH}")
report_lines.append(f"Output CSV: {OUTPUT_CSV}")
report_lines.append("")

report_lines.append("OVERVIEW")
report_lines.append(f"- Sheets in workbook: {len(sheet_names)}")
report_lines.append(f"- Sheets parsed: {len(all_sheets)}")
report_lines.append(f"- Rows exported: {len(all_data)}")
report_lines.append(f"- Carriers found: {carrier_rates_df['carrier'].nunique(dropna=True)}")
report_lines.append("")

report_lines.append("STATUS")
if errors:
    report_lines.append(f"- ERROR: {len(errors)} issue(s)")
    for item in errors:
        report_lines.append(f"  - {item}")
else:
    report_lines.append("- ERROR: none")

if warnings:
    report_lines.append(f"- WARN: {len(warnings)} warning group(s)")
    for item in warnings:
        report_lines.append(f"  - {item}")
else:
    report_lines.append("- WARN: none")

if not errors and not warnings:
    report_lines.append("- RESULT: OK (no errors or warnings)")
else:
    report_lines.append("- RESULT: CHECK WARNINGS/ERRORS")
report_lines.append("")

report_lines.append("STATE COMPLETENESS")
report_lines.append(f"- Rows with missing from_state: {missing_from_state}")
report_lines.append(f"- Rows with missing to_state: {missing_to_state}")
report_lines.append(f"- Routes with any missing state: {len(missing_state_rows)}")
if not missing_state_rows.empty:
    report_lines.append("- Sample routes with missing states (up to 10):")
    for _, row in missing_state_rows.head(10).iterrows():
        report_lines.append(
            f"  - {row['carrier']}: {row['from']} -> {row['to']} "
            f"(from_state={row['from_state']}, to_state={row['to_state']})"
        )
report_lines.append("")

report_lines.append("NUMERIC COMPLETENESS (SUPPORTED SECTIONS ONLY)")
report_lines.append(f"- Numeric values in supported section tables: {section_numeric_total}")
report_lines.append(f"- Numeric values parsed into matrix records: {parsed_matrix_numeric_total}")
report_lines.append(f"- Numeric values in final output (after transform): {final_output_numeric_total}")
if parsed_matrix_numeric_total < section_numeric_total:
    report_lines.append("- Note: some supported-section numeric values were not parsed.")
if final_output_numeric_total != parsed_matrix_numeric_total:
    report_lines.append("- Note: final count differs due to row transformation rules.")
report_lines.append("")

report_lines.append("CARRIER COMPLETENESS")
carrier_col = "carrier"
routes_col = "routes"
miss_pass_col = "missing_pass"
miss_lcv_col = "missing_lcv"

w_carrier = max(len(carrier_col), max(len(str(v)) for v in completeness_summary_df["carrier"]))
w_routes = max(len(routes_col), max(len(str(int(v))) for v in completeness_summary_df["routes"]))
w_miss_pass = max(len(miss_pass_col), max(len(str(int(v))) for v in completeness_summary_df["missing_pass"]))
w_miss_lcv = max(len(miss_lcv_col), max(len(str(int(v))) for v in completeness_summary_df["missing_lcv"]))

header = (
    f"{carrier_col:<{w_carrier}} | "
    f"{routes_col:>{w_routes}} | "
    f"{miss_pass_col:>{w_miss_pass}} | "
    f"{miss_lcv_col:>{w_miss_lcv}}"
)
report_lines.append(header)
report_lines.append("-" * len(header))

for _, row in completeness_summary_df.iterrows():
    report_lines.append(
        f"{str(row['carrier']):<{w_carrier}} | "
        f"{int(row['routes']):>{w_routes}} | "
        f"{int(row['missing_pass']):>{w_miss_pass}} | "
        f"{int(row['missing_lcv']):>{w_miss_lcv}}"
    )
report_lines.append("")

report_lines.append("DETAILS")
report_lines.append("- Full per-route rates are intentionally omitted for concise reporting.")
report_lines.append("- Use new-template.csv for route-level rate data.")
report_lines.append(line)

full_report_text = "\n".join(report_lines)

# Save full text report
report_path = Path(OUTPUT_CSV).with_name("new-template-report.txt")
report_path.write_text(full_report_text, encoding="utf-8")

print(full_report_text)
print(f"\nSaved to: {report_path}")

==============================================================================
RATE IMPORT REPORT
Generated: 2026-05-15 14:33:24
==============================================================================
Workbook path: ac-test.xlsx
Output CSV: new-template.csv

OVERVIEW
- Sheets in workbook: 17
- Sheets parsed: 17
- Rows exported: 347
- Carriers found: 17

STATUS
- ERROR: none
- WARN: none
- RESULT: OK (no errors or warnings)

NUMERIC COMPLETENESS (SUPPORTED SECTIONS ONLY)
- Numeric values in supported section tables: 665
- Numeric values parsed into matrix records: 665
- Numeric values in final output (after transform): 694
- Note: final count differs due to row transformation rules.

CARRIER COMPLETENESS
carrier                        | routes | missing_pass | missing_lcv
--------------------------------------------------------------------
A1                             |      6 |            0 |           0
ACE CAR CARRIERS               |      2 |            0 |           0
ALFIES TOWING                  |      2 |            0 |           0
AUTOCARE                       |    156 |            0 |           0
AUTOMOVER                      |     11 |            0 |           0
CAIRNS CAR CARRIERS            |      2 |            0 |           0
CAPITAL TOWING                 |      2 |            0 |           0
CARWAYS                        |     18 |            0 |           0
GTTKAL                         |      4 |            0 |           0
HAUL CAR                       |      2 |            0 |           0
HUNTER UNITED                  |     10 |            0 |           0
IAT TRANSPORT                  |     18 |            0 |           0
MACKAY CAR & COMMERCIAL        |      2 |            0 |           0
MELCREST                       |     42 |            0 |           0
NEWCASTLE VEHICLE TRANSPORTERS |      2 |            0 |           0
SHIPPING                       |     11 |            0 |           0
SMB                            |     57 |            0 |           0

DETAILS
- Full per-route rates are intentionally omitted for concise reporting.
- Use new-template.csv for route-level rate data.
==============================================================================

Saved to: new-template-report.txt